CREATE TABLE IF NOT EXISTS `xt_article_inspect_keywords` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(64) NOT NULL DEFAULT '',
  `match_type` VARCHAR(32) NOT NULL,
  `risk_level` VARCHAR(32) NOT NULL,
  `suggest_action` VARCHAR(32) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `remark` TEXT NULL,
  `creator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `creator_name` VARCHAR(128) NOT NULL DEFAULT '',
  `updater_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `updater_name` VARCHAR(128) NOT NULL DEFAULT '',
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_org_enabled_category` (`orgid`, `enabled`, `category`),
  KEY `idx_org_name` (`orgid`, `name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_keyword_scopes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `keyword_id` BIGINT UNSIGNED NOT NULL,
  `scope` VARCHAR(32) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_org_keyword` (`orgid`, `keyword_id`),
  UNIQUE KEY `uk_org_keyword_scope` (`orgid`, `keyword_id`, `scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `task_no` VARCHAR(64) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `article_state_filter` VARCHAR(64) NOT NULL DEFAULT '',
  `publish_time_start` DATETIME NULL,
  `publish_time_end` DATETIME NULL,
  `article_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `title_like` VARCHAR(255) NOT NULL DEFAULT '',
  `include_body` TINYINT(1) NOT NULL DEFAULT 1,
  `scope_override_mode` VARCHAR(32) NOT NULL DEFAULT '',
  `scope_snapshot` LONGTEXT NULL,
  `request_snapshot` LONGTEXT NULL,
  `rule_snapshot` LONGTEXT NULL,
  `total_scanned` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `hit_articles` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `hit_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `skip_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `fail_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `batch_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `duration_ms` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `creator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `creator_name` VARCHAR(128) NOT NULL DEFAULT '',
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  KEY `idx_org_status_create` (`orgid`, `status`, `create_at`),
  KEY `idx_org_creator_create` (`orgid`, `creator_id`, `create_at`),
  KEY `idx_org_time_range` (`orgid`, `publish_time_start`, `publish_time_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_task_keywords` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `keyword_id` BIGINT UNSIGNED NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_org_task` (`orgid`, `task_id`),
  KEY `idx_org_keyword` (`orgid`, `keyword_id`),
  UNIQUE KEY `uk_org_task_keyword` (`orgid`, `task_id`, `keyword_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_results` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `article_id` BIGINT UNSIGNED NOT NULL,
  `article_title` VARCHAR(255) NOT NULL DEFAULT '',
  `article_state` TINYINT NOT NULL DEFAULT 0,
  `publish_at_time` DATETIME NULL,
  `risk_level` VARCHAR(32) NOT NULL,
  `suggest_action` VARCHAR(32) NOT NULL,
  `hit_fields_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `hit_keywords_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `hit_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `disposition_status` VARCHAR(32) NOT NULL,
  `latest_action_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `latest_operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `latest_operator_name` VARCHAR(128) NOT NULL DEFAULT '',
  `latest_action_at` DATETIME NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_task_article` (`orgid`, `task_id`, `article_id`),
  KEY `idx_org_task_risk` (`orgid`, `task_id`, `risk_level`),
  KEY `idx_org_disposition_update` (`orgid`, `disposition_status`, `update_at`),
  KEY `idx_org_article_update` (`orgid`, `article_id`, `update_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_result_hits` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `result_id` BIGINT UNSIGNED NOT NULL,
  `article_id` BIGINT UNSIGNED NOT NULL,
  `keyword_id` BIGINT UNSIGNED NOT NULL,
  `keyword_text` VARCHAR(255) NOT NULL DEFAULT '',
  `category` VARCHAR(64) NOT NULL DEFAULT '',
  `field_name` VARCHAR(64) NOT NULL DEFAULT '',
  `match_type` VARCHAR(32) NOT NULL,
  `risk_level` VARCHAR(32) NOT NULL,
  `suggest_action` VARCHAR(32) NOT NULL,
  `matched_text` TEXT NULL,
  `snippet` TEXT NULL,
  `position_start` INT NOT NULL DEFAULT 0,
  `position_end` INT NOT NULL DEFAULT 0,
  `rule_snapshot` LONGTEXT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_org_result` (`orgid`, `result_id`),
  KEY `idx_org_task_keyword` (`orgid`, `task_id`, `keyword_id`),
  KEY `idx_org_article_field` (`orgid`, `article_id`, `field_name`),
  KEY `idx_org_risk_create` (`orgid`, `risk_level`, `create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_actions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `action_no` VARCHAR(64) NOT NULL,
  `action_type` VARCHAR(32) NOT NULL,
  `task_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `batch_scope` VARCHAR(32) NOT NULL DEFAULT '',
  `target_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `success_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `fail_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `skip_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL,
  `reason` TEXT NULL,
  `request_snapshot` LONGTEXT NULL,
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `operator_name` VARCHAR(128) NOT NULL DEFAULT '',
  `request_id` VARCHAR(128) NOT NULL DEFAULT '',
  `source_ip` VARCHAR(64) NOT NULL DEFAULT '',
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_action_no` (`action_no`),
  KEY `idx_org_action_type_create` (`orgid`, `action_type`, `create_at`),
  KEY `idx_org_task_create` (`orgid`, `task_id`, `create_at`),
  KEY `idx_org_operator_create` (`orgid`, `operator_id`, `create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_operation_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `action_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `task_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `result_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `article_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `operation_type` VARCHAR(32) NOT NULL,
  `before_state` VARCHAR(32) NOT NULL DEFAULT '',
  `after_state` VARCHAR(32) NOT NULL DEFAULT '',
  `status` VARCHAR(32) NOT NULL,
  `reason` TEXT NULL,
  `summary` TEXT NULL,
  `request_snapshot` LONGTEXT NULL,
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `operator_name` VARCHAR(128) NOT NULL DEFAULT '',
  `request_id` VARCHAR(128) NOT NULL DEFAULT '',
  `source_ip` VARCHAR(64) NOT NULL DEFAULT '',
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_org_article_create` (`orgid`, `article_id`, `create_at`),
  KEY `idx_org_task_create` (`orgid`, `task_id`, `create_at`),
  KEY `idx_org_operator_create` (`orgid`, `operator_id`, `create_at`),
  KEY `idx_org_result` (`orgid`, `result_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `xt_article_inspect_field_change_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` BIGINT UNSIGNED NOT NULL,
  `action_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `task_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `result_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `article_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `field_name` VARCHAR(64) NOT NULL,
  `before_value` LONGTEXT NULL,
  `after_value` LONGTEXT NULL,
  `diff_summary` TEXT NULL,
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `operator_name` VARCHAR(128) NOT NULL DEFAULT '',
  `request_id` VARCHAR(128) NOT NULL DEFAULT '',
  `source_ip` VARCHAR(64) NOT NULL DEFAULT '',
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_org_article_create` (`orgid`, `article_id`, `create_at`),
  KEY `idx_org_action` (`orgid`, `action_id`),
  KEY `idx_org_field_create` (`orgid`, `field_name`, `create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
